### ISSUE TITLE
Failed to unlock 950 XL due to looking at the wrong partition?

### ISSUE THREAD

**Issue by Tourniquet88** [ReneLergner/WPinternals#19]
I just downloaded the "CI: Disable trimming" commit artifact and tried to unlock my 950 XL.

It saidly failed with "Could not find file 'J:\Windows\System32\BOOT\winload.efi'. J in this case is the EFIESP and that file is indeed not there. It is however in the MainOS Partition in K:\.

`2021-03-06 18:15:40.992: Custom flash succeeded!
2021-03-06 18:15:41.447: Rebooting phone
2021-03-06 18:15:41.448: Phone performs hard exit
2021-03-06 18:15:41.479: Lumia disconnected
2021-03-06 18:15:49.283: Flash App Type: BootManager
2021-03-06 18:15:49.283: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2021-03-06 18:15:49.283: Device path: \\?\USB#VID_045E&PID_0A02#7&1ca76ca2&0&3#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2021-03-06 18:15:49.283: Connected device: Lumia
2021-03-06 18:15:49.283: Mode: Bootloader
2021-03-06 18:15:49.310: Bootmanager: 2.48
2021-03-06 18:15:49.310: Bootmanager protocol: 2.6
2021-03-06 18:15:49.310: Flash app: 2.75
2021-03-06 18:15:49.310: Flash protocol: 2.41
2021-03-06 18:15:49.310: SecureBoot: Disabled (Platform Secure Boot: Disabled, UEFI Secure Boot: Disabled)
2021-03-06 18:15:49.310: Flash app security: Disabled (FFU security: Disabled, RDC: Not found, Authenticated: False)
2021-03-06 18:15:49.310: JTAG: Enabled
2021-03-06 18:15:49.528: Phone type: RM-1085
2021-03-06 18:15:49.528: Product code: 059X4T1
2021-03-06 18:15:49.528: Root key hash: xxx
2021-03-06 18:15:49.528: Firmware version: 01078.00053.16236.35000
2021-03-06 18:15:49.528: IMEI: xxx
2021-03-06 18:15:49.528: Flash app: 2.75
2021-03-06 18:15:49.528: Flash protocol: 2.41
2021-03-06 18:15:49.528: SecureBoot: Disabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
2021-03-06 18:15:49.528: Flash app security: Enabled (FFU security: Enabled, RDC: Not found, Authenticated: False)
2021-03-06 18:15:49.528: JTAG: Disabled
2021-03-06 18:15:49.562: Hashing resources...
2021-03-06 18:15:49.709: Flashing...
2021-03-06 18:15:50.759: Rebooting phone
2021-03-06 18:15:50.760: Waiting for phone to disconnect...
2021-03-06 18:15:50.775: Lumia disconnected
2021-03-06 18:15:50.776: Waiting for phone to connect...
2021-03-06 18:15:59.145: Flash App Type: BootManager
2021-03-06 18:15:59.145: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2021-03-06 18:15:59.145: Device path: \\?\USB#VID_045E&PID_0A02#7&1ca76ca2&0&3#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2021-03-06 18:15:59.145: Connected device: Lumia
2021-03-06 18:15:59.145: Mode: Bootloader
2021-03-06 18:15:59.172: Bootmanager: 2.48
2021-03-06 18:15:59.172: Bootmanager protocol: 2.6
2021-03-06 18:15:59.172: Flash app: 2.75
2021-03-06 18:15:59.172: Flash protocol: 2.41
2021-03-06 18:15:59.172: SecureBoot: Disabled (Platform Secure Boot: Disabled, UEFI Secure Boot: Disabled)
2021-03-06 18:15:59.172: Flash app security: Disabled (FFU security: Disabled, RDC: Not found, Authenticated: False)
2021-03-06 18:15:59.172: JTAG: Enabled
2021-03-06 18:15:59.293: Flash app: 2.75
2021-03-06 18:15:59.293: Flash protocol: 2.41
2021-03-06 18:15:59.293: SecureBoot: Disabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
2021-03-06 18:15:59.293: Flash app security: Enabled (FFU security: Enabled, RDC: Not found, Authenticated: False)
2021-03-06 18:15:59.293: JTAG: Disabled
2021-03-06 18:15:59.327: Rebooting phone to Mass Storage mode...
2021-03-06 18:15:59.327: Preparing phone for Mass Storage Mode
2021-03-06 18:16:00.272: Rebooting phone
2021-03-06 18:16:00.287: Lumia disconnected
2021-03-06 18:16:08.543: Flash App Type: BootManager
2021-03-06 18:16:08.543: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2021-03-06 18:16:08.543: Device path: \\?\USB#VID_045E&PID_0A02#7&1ca76ca2&0&3#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2021-03-06 18:16:08.543: Connected device: Lumia
2021-03-06 18:16:08.543: Mode: Bootloader
2021-03-06 18:16:08.572: Bootmanager: 2.48
2021-03-06 18:16:08.572: Bootmanager protocol: 2.6
2021-03-06 18:16:08.572: Flash app: 2.75
2021-03-06 18:16:08.572: Flash protocol: 2.41
2021-03-06 18:16:08.572: SecureBoot: Disabled (Platform Secure Boot: Disabled, UEFI Secure Boot: Disabled)
2021-03-06 18:16:08.572: Flash app security: Disabled (FFU security: Disabled, RDC: Not found, Authenticated: False)
2021-03-06 18:16:08.572: JTAG: Enabled
2021-03-06 18:16:10.712: Rebooting phone
2021-03-06 18:16:10.712: Phone performs hard exit
2021-03-06 18:16:10.739: Lumia disconnected
2021-03-06 18:16:18.580: Flash App Type: BootManager
2021-03-06 18:16:18.580: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2021-03-06 18:16:18.580: Device path: \\?\USB#VID_045E&PID_0A02#7&1ca76ca2&0&3#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2021-03-06 18:16:18.580: Connected device: Lumia
2021-03-06 18:16:18.580: Mode: Bootloader
2021-03-06 18:16:18.580: Waiting for Mass Storage Mode (1)...
2021-03-06 18:16:24.556: Lumia disconnected
2021-03-06 18:16:27.360: Mass storage arrived: \\?\USBSTOR#Disk&Ven_MSFT&Prod_Phone_MMC_Stor&Rev_1.00#15000000-4A45-80F3-0000-000000000000&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}
2021-03-06 18:16:27.360: Start new thread for getting metadata.
2021-03-06 18:16:32.277: Mass storage arrived: \\.\K:
2021-03-06 18:16:32.277: Start new thread for getting metadata.
2021-03-06 18:16:32.277: Mass storage arrived: \\.\K:
2021-03-06 18:16:32.277: Start new thread for getting metadata.
2021-03-06 18:16:32.277: Mass storage arrived: \\.\K:
2021-03-06 18:16:32.277: Start new thread for getting metadata.
2021-03-06 18:16:32.277: Mass storage arrived: \\.\K:
2021-03-06 18:16:32.277: Start new thread for getting metadata.
2021-03-06 18:16:32.277: Mass storage arrived: \\.\K:
2021-03-06 18:16:32.277: Start new thread for getting metadata.
2021-03-06 18:16:32.277: Mass storage arrived: \\.\K:
2021-03-06 18:16:32.277: Start new thread for getting metadata.
2021-03-06 18:16:32.277: Mass storage arrived: \\.\K:
2021-03-06 18:16:32.277: Start new thread for getting metadata.
2021-03-06 18:16:32.278: Mass storage arrived: \\.\K:
2021-03-06 18:16:32.278: Start new thread for getting metadata.
2021-03-06 18:16:32.278: Mass storage arrived: \\.\K:
2021-03-06 18:16:32.278: Start new thread for getting metadata.
2021-03-06 18:16:32.606: Found device on interface: 53f56307-b6bf-11d0-94f2-00a0c91efb8b
2021-03-06 18:16:32.606: Device path: \\?\USBSTOR#Disk&Ven_MSFT&Prod_Phone_MMC_Stor&Rev_1.00#15000000-4A45-80F3-0000-000000000000&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}
2021-03-06 18:16:32.606: Connected device: Lumia
2021-03-06 18:16:32.606: Mode: Mass storage mode
2021-03-06 18:16:32.608: Create backup partition...
2021-03-06 18:16:33.369: Attempt patch: SecureBootHack-V2-EFIESP
2021-03-06 18:16:33.374: Pattern: 0, 0
2021-03-06 18:16:33.374: Pattern: 1, 0
2021-03-06 18:16:33.374: Pattern: 2, 0
2021-03-06 18:16:33.374: Pattern: 3, 0
2021-03-06 18:16:33.374: Pattern: 4, 0
2021-03-06 18:16:33.374: Apply: 10.0.10586.318
2021-03-06 18:16:33.374: Edit BCD
2021-03-06 18:16:33.377: Boot optimization...
2021-03-06 18:16:33.377: Attempt patch: SecureBootHack-MainOS
2021-03-06 18:16:33.393: Error: Could not find file 'J:\Windows\System32\BOOT\winload.efi'.
2021-03-06 18:16:33.401:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at WPinternals.FilePatcher..ctor(String FilePath)
   at WPinternals.PatchEngine.Patch(String PatchDefinition)
   at WPinternals.LumiaUnlockBootloaderViewModel.LumiaUnlockUEFI(PhoneNotifierViewModel Notifier, String ProfileFFUPath, String EDEPath, String SupportedFFUPath, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus, ExitSuccess ExitSuccess, ExitFailure ExitFailure, Boolean ExperimentalSpecBEFIESPUnlock, Boolean ExperimentalSpecAEFIESPUnlock, Boolean ReUnlockDevice)
2021-03-06 18:16:33.401: Could not find file 'J:\Windows\System32\BOOT\winload.efi'.
`

**Comment by gus33000** [comment]
Hi

Please try the updated version: https://github.com/ReneLergner/WPinternals/releases/tag/2.9
