### ISSUE TITLE
Error: Failed to write to pipe: 4E4F4B58434242 when unlock Lumia 930

### ISSUE THREAD

**Issue by Jack-Myth** [ReneLergner/WPinternals#43]
I have tried almost every version(2.8;2.9;2.9.2), Every version report this error.

2022-07-14 19:53:45.315: Found device on interface: 08324f9c-b621-435c-859b-ae4652481b7c
2022-07-14 19:53:45.315: Device path: \\?\USB#VID_0421&PID_06FC&MI_03#8&2f2b5c5b&0&0003#{08324f9c-b621-435c-859b-ae4652481b7c}
2022-07-14 19:53:45.315: Connected device: Lumia
2022-07-14 19:53:45.315: Mode: Normal
2022-07-14 19:53:45.319: Operator: 000-HK
2022-07-14 19:53:45.320: Manufacturer Model Name: RM-1045_1044
2022-07-14 19:53:45.333: Product Code: 059W5D7
2022-07-14 19:53:45.334: Firmware: 02540.00019.15053.26005
2022-07-14 19:53:45.335: HWID: 2003
2022-07-14 19:53:45.343: IMEI: 354244060593536
2022-07-14 19:53:45.347: Public ID: 86 9D 06 A0 88 EA 0E F5 93 42 A0 9E C1 E9 9B 46 2B 75 6F CF
2022-07-14 19:53:45.349: Bluetooth MAC: 74 E2 8C 2D 7D ED
2022-07-14 19:53:45.356: WLAN MAC 1: 74 E2 8C 2D F3 58
2022-07-14 19:53:45.362: WLAN MAC 2: 74 E2 8C 2D F3 59
2022-07-14 19:53:45.368: WLAN MAC 3: 74 E2 8C 2D F3 5A
2022-07-14 19:53:45.374: WLAN MAC 4: 74 E2 8C 2D F3 5B
2022-07-14 19:53:45.379: Bootloader Security: Enabled
2022-07-14 19:53:45.385: Simlock: Unlocked
2022-07-14 19:53:45.439: Boot policy: Unsecure
2022-07-14 19:53:45.439: DB: SecureProduction
2022-07-14 19:53:45.439: DBX: SecureProduction
2022-07-14 19:53:45.439: KEK: SecureProduction
2022-07-14 19:53:45.439: PK: SecureProduction
2022-07-14 19:53:58.435: Start unlock. Phone needs to switch to Flash-mode
2022-07-14 19:53:58.435: In order to start unlocking the bootloader, the phone needs to be switched to Flash-mode.
2022-07-14 19:53:59.381: Switching to Flash-mode
2022-07-14 19:53:59.382: Rebooting phone to Flash mode
2022-07-14 19:53:59.384: Rebooting phone to Flash mode...
2022-07-14 19:54:06.006: Lumia disconnected
2022-07-14 19:54:10.862: Flash App Type: FlashApp
2022-07-14 19:54:10.865: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2022-07-14 19:54:10.865: Device path: \\?\USB#VID_0421&PID_0714#6&3365fbaf&0&5#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2022-07-14 19:54:10.865: Connected device: Lumia
2022-07-14 19:54:10.865: Mode: Flash
2022-07-14 19:54:11.104: Phone type: RM-1087
2022-07-14 19:54:11.104: Product code: 059W5D7
2022-07-14 19:54:11.104: Root key hash: 800EEB508F7BBDF12A19262621FD837297A3B062FE2A7078C0F3167E57F21217
2022-07-14 19:54:11.104: Firmware version: 02540.00019.15053.26000
2022-07-14 19:54:11.104: IMEI: 354244060593536
2022-07-14 19:54:11.104: Flash app: 2.59
2022-07-14 19:54:11.104: Flash protocol: 2.34
2022-07-14 19:54:11.104: SecureBoot: Disabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
2022-07-14 19:54:11.104: Flash app security: Enabled (FFU security: Enabled, RDC: Not found, Authenticated: False)
2022-07-14 19:54:11.104: JTAG: Disabled
2022-07-14 19:54:47.866: Windows Phone Internals version 2.9.7893.25219
2022-07-14 19:54:47.869: Copyright Heathcliff74 / wpinternals.net
2022-07-14 19:54:48.078: Flash App Type: FlashApp
2022-07-14 19:54:48.082: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2022-07-14 19:54:48.082: Device path: \\?\usb#vid_0421&pid_0714#6&3365fbaf&0&5#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2022-07-14 19:54:48.082: Connected device: Lumia
2022-07-14 19:54:48.082: Mode: Flash
2022-07-14 19:54:48.160: Security flags: 0x00007BFF
2022-07-14 19:54:48.466: Platform Name: Nokia.MSM8974.P6180.2.2
2022-07-14 19:54:48.484: Public ID: 86 9D 06 A0 88 EA 0E F5 93 42 A0 9E C1 E9 9B 46 2B 75 6F CF
2022-07-14 19:54:48.502: Root Key Hash: 80 0E EB 50 8F 7B BD F1 2A 19 26 26 21 FD 83 72 97 A3 B0 62 FE 2A 70 78 C0 F3 16 7E 57 F2 12 17
2022-07-14 19:54:48.502: Platform Secure Boot Status: True
2022-07-14 19:54:48.502: Uefi Secure Boot Status: False
2022-07-14 19:54:48.502: Effective Secure Boot Status: False
2022-07-14 19:54:48.502: Bootloader Security Qfuse Status: True
2022-07-14 19:54:48.502: Bootloader Security Authentication Status: False
2022-07-14 19:54:48.502: Bootloader Security Rdc Status: False
2022-07-14 19:54:48.502: Effective Bootloader Security Status: True
2022-07-14 19:54:48.502: Native Debug Status: False
2022-07-14 19:54:48.642: Charging status: 22% - 424 mA (charging)
2022-07-14 19:54:48.810: Phone type: RM-1087
2022-07-14 19:54:48.810: Product code: 059W5D7
2022-07-14 19:54:48.810: Root key hash: 800EEB508F7BBDF12A19262621FD837297A3B062FE2A7078C0F3167E57F21217
2022-07-14 19:54:48.810: Firmware version: 02540.00019.15053.26000
2022-07-14 19:54:48.810: IMEI: 354244060593536
2022-07-14 19:54:48.810: Flash app: 2.59
2022-07-14 19:54:48.810: Flash protocol: 2.34
2022-07-14 19:54:48.810: SecureBoot: Disabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
2022-07-14 19:54:48.810: Flash app security: Enabled (FFU security: Enabled, RDC: Not found, Authenticated: False)
2022-07-14 19:54:48.810: JTAG: Disabled
2022-07-14 19:54:48.810: Bootloader: Lumia Bootloader Spec B
2022-07-14 19:54:48.810: ProductCode: 059W5D7
2022-07-14 19:54:48.810: ProductType: RM-1087
2022-07-14 19:54:54.870: FFU not added, because it was already present in the repository.
2022-07-14 19:54:54.871: Emergency files not added, because they were already present in the repository.
2022-07-14 19:54:54.888: FFU not added, because it was already present in the repository.
2022-07-14 19:54:54.888: Unlock Bootloader
2022-07-14 19:54:54.888: Processing resources:
2022-07-14 19:54:54.888: Profile FFU: C:\Users\JackMyth\Desktop\RM1045_02540.00019.15053.26005_RETAIL_prod_signed_1044_01B8EF_000-HK.ffu
2022-07-14 19:54:54.888: EDE file: C:\Users\JackMyth\Desktop\MPRG8974_fh.ede
2022-07-14 19:54:54.888: Donor-FFU with supported OS version: C:\Users\JackMyth\Desktop\RM1087_Lumia930_10240.16384_02540.00019.15236.45002_RETAIL_prod_signed_1000_028F87_UNI-CN.ffu
2022-07-14 19:54:55.173: Assembling data for unlock
2022-07-14 19:54:55.173: Assembling data for unlock
2022-07-14 19:54:55.187: Attempt patch: SecureBootHack-V2-EFIESP
2022-07-14 19:54:55.188: Pattern: 0, 0
2022-07-14 19:54:55.188: Pattern: 1, 0
2022-07-14 19:54:55.188: Pattern: 2, 0
2022-07-14 19:54:55.188: Pattern: 3, 0
2022-07-14 19:54:55.188: Pattern: 4, 0
2022-07-14 19:54:55.188: Pattern: 5, 0
2022-07-14 19:54:55.188: Pattern: 6, 0
2022-07-14 19:54:55.188: Pattern: 7, 0
2022-07-14 19:54:55.188: Pattern: 8, 0
2022-07-14 19:54:55.188: Pattern: 9, 0
2022-07-14 19:54:55.188: Pattern: 10, 0
2022-07-14 19:54:55.188: Pattern: 11, 0
2022-07-14 19:54:55.188: Pattern: 12, 0
2022-07-14 19:54:55.188: Pattern: 13, 0
2022-07-14 19:54:55.188: Pattern: 14, 0
2022-07-14 19:54:55.188: Pattern: 15, 0
2022-07-14 19:54:55.188: Pattern: 16, 0
2022-07-14 19:54:55.188: Pattern: 17, 0
2022-07-14 19:54:55.188: Pattern: 18, 0
2022-07-14 19:54:55.189: Pattern: 19, 0
2022-07-14 19:54:55.189: Pattern: 20, 0
2022-07-14 19:54:55.189: Donor-FFU: C:\Users\JackMyth\Desktop\RM1087_Lumia930_10240.16384_02540.00019.15236.45002_RETAIL_prod_signed_1000_028F87_UNI-CN.ffu
2022-07-14 19:54:55.204: Taking mobilestartup.efi from donor-FFU
2022-07-14 19:54:55.206: Attempt patch: SecureBootHack-V2-EFIESP
2022-07-14 19:54:55.208: Apply: 10.0.10240.16384
2022-07-14 19:54:55.209: Edit BCD
2022-07-14 19:54:55.249: Enabling Test Signing
2022-07-14 19:54:55.249: Enabling Test Signing
2022-07-14 19:58:01.078: Error on USB port!
2022-07-14 19:58:01.078: Device: Lumia BootMgr - Microsoft
2022-07-14 19:58:01.078: Last written: 4E4F4B44
2022-07-14 19:58:01.081: Error: Failed to read from pipe.
2022-07-14 19:58:01.082:     Error: Failed to read pipe on WinUSB device.
2022-07-14 19:58:01.083:        at MadWizard.WinUSBNet.API.WinUSBDevice.ReadPipe(Int32 ifaceIndex, Byte pipeID, Byte[] buffer, Int32 offset, Int32 bytesToRead, UInt32& bytesRead)
   at MadWizard.WinUSBNet.USBPipe.Read(Byte[] buffer, Int32 offset, Int32 length)
2022-07-14 19:58:01.084:         Error: 
2022-07-14 19:58:01.100: Lumia disconnected
2022-07-14 19:58:01.283: Error on USB port!
2022-07-14 19:58:01.283: Device: Lumia BootMgr - Microsoft
2022-07-14 19:58:01.283: Last written: 4E4F4B58434242
2022-07-14 19:58:01.283: Error: Failed to write to pipe: 4E4F4B58434242
2022-07-14 19:58:01.283:     Error: Failed to write pipe on WinUSB device.
2022-07-14 19:58:01.283:        at MadWizard.WinUSBNet.API.WinUSBDevice.WritePipe(Int32 ifaceIndex, Byte pipeID, Byte[] buffer, Int32 offset, Int32 length)
   at MadWizard.WinUSBNet.USBPipe.Write(Byte[] buffer, Int32 offset, Int32 length)
2022-07-14 19:58:01.283:         Error: 
2022-07-14 19:58:01.283: Error: Failed to write to pipe: 4E4F4B58434242
2022-07-14 19:58:01.284:    at MadWizard.WinUSBNet.USBPipe.LogAndThrowException(Exception Ex)
   at MadWizard.WinUSBNet.USBPipe.Write(Byte[] buffer, Int32 offset, Int32 length)
   at WPinternals.NokiaPhoneModel.ExecuteRawMethod(Byte[] RawMethod, Int32 Length)
   at WPinternals.NokiaPhoneModel.ExecuteRawMethod(Byte[] RawMethod)
   at WPinternals.NokiaFlashModel.SwitchToBootManagerContext(Boolean DisableTimeOut)
   at WPinternals.LumiaUnlockBootloaderViewModel.GetGptChunk(NokiaFlashModel FlashModel, UInt32 Size)
   at WPinternals.LumiaV2UnlockBootViewModel.LumiaV2CustomFlashInternal(PhoneNotifierViewModel Notifier, String FFUPath, Boolean PerformFullFlashFirst, Boolean SkipWrite, List`1 FlashParts, Boolean DoResetFirst, Boolean ClearFlashingStatusAtEnd, Boolean CheckSectorAlignment, Boolean ShowProgress, Boolean Experimental, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus, ExitSuccess ExitSuccess, ExitFailure ExitFailure, String ProgrammerPath)
   at WPinternals.LumiaV2UnlockBootViewModel.LumiaV2CustomFlash(PhoneNotifierViewModel Notifier, String FFUPath, Boolean PerformFullFlashFirst, Boolean SkipWrite, List`1 FlashParts, Boolean DoResetFirst, Boolean ClearFlashingStatusAtEnd, Boolean CheckSectorAlignment, Boolean ShowProgress, Boolean Experimental, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus, ExitSuccess ExitSuccess, ExitFailure ExitFailure, String ProgrammerPath)
   at WPinternals.LumiaUnlockBootloaderViewModel.LumiaFlashParts(PhoneNotifierViewModel Notifier, String FFUPath, Boolean PerformFullFlashFirst, Boolean SkipWrite, List`1 Parts, Boolean DoResetFirst, Boolean ClearFlashingStatusAtEnd, Boolean CheckSectorAlignment, Boolean ShowProgress, Boolean Experimental, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus, ExitSuccess ExitSuccess, ExitFailure ExitFailure, String EDEPath)
   at WPinternals.LumiaUnlockBootloaderViewModel.LumiaUnlockUEFI(PhoneNotifierViewModel Notifier, String ProfileFFUPath, String EDEPath, String SupportedFFUPath, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus, ExitSuccess ExitSuccess, ExitFailure ExitFailure, Boolean ExperimentalSpecBEFIESPUnlock, Boolean ExperimentalSpecAEFIESPUnlock, Boolean ReUnlockDevice)
2022-07-14 19:58:01.284:     Error: Failed to write pipe on WinUSB device.
2022-07-14 19:58:01.284:        at MadWizard.WinUSBNet.API.WinUSBDevice.WritePipe(Int32 ifaceIndex, Byte pipeID, Byte[] buffer, Int32 offset, Int32 length)
   at MadWizard.WinUSBNet.USBPipe.Write(Byte[] buffer, Int32 offset, Int32 length)
2022-07-14 19:58:01.284:         Error: 
2022-07-14 19:58:01.284: Failed to write to pipe: 4E4F4B58434242

**Comment by Jack-Myth** [comment]
Find the result, The USB port on my PC have some issues, It can flash original FFU but unable to do the unlock. I change a computer and the problem is gone.
