### ISSUE TITLE
Not working for lumia 735?

### ISSUE THREAD

**Issue by StarNumber12046** [ReneLergner/WPinternals#49]
### Description

The FFU-image you selected for profiling does not have a supported OS-version. 

### Steps To Reproduce

1. Download files for RM-1041 (prod id 059W946)
2. Try to unlock bootloader
3. The error

### Expected behavior

It should allow me to unlock the bootloader

### WPinternals Version

v2.9.2

### Windows Version

windows 11 22h2 10.0.22621.1485

### Phone model

Nokia Lumia 735

### Relevant Assets

2023-04-09 15:36:24.512: Windows Phone Internals version 2.9.7894.11970
2023-04-09 15:36:24.554: Copyright Heathcliff74 / wpinternals.net
2023-04-09 15:36:28.513: Found device on interface: 08324f9c-b621-435c-859b-ae4652481b7c
2023-04-09 15:36:28.513: Device path: \\?\usb#vid_0421&pid_06fc&mi_03#6&1b948965&0&0003#{08324f9c-b621-435c-859b-ae4652481b7c}
2023-04-09 15:36:28.514: Connected device: Lumia
2023-04-09 15:36:28.514: Mode: Normal
2023-04-09 15:36:28.657: Operator: 000-IT
2023-04-09 15:36:28.660: Manufacturer Model Name: RM-1038_1012
2023-04-09 15:36:28.747: Product Code: 059W558
2023-04-09 15:36:28.749: Firmware: 02177.00000.15184.36004
2023-04-09 15:36:28.761: HWID: 1000
2023-04-09 15:36:28.784: IMEI: 354265063491840
2023-04-09 15:36:28.793: Public ID: A1 FA 2A 0E 93 D8 84 83 A6 DD D9 52 19 D1 2A A5 AC A7 55 D3
2023-04-09 15:36:28.798: Bluetooth MAC: D0 92 9E 7E 7C 93
2023-04-09 15:36:28.816: WLAN MAC 1: D0 92 9E 80 CC 9C
2023-04-09 15:36:28.835: WLAN MAC 2: D0 92 9E 80 CC 9D
2023-04-09 15:36:28.853: WLAN MAC 3: D0 92 9E 80 CC 9E
2023-04-09 15:36:28.871: WLAN MAC 4: D0 92 9E 80 CC 9F
2023-04-09 15:36:28.889: Bootloader Security: Enabled
2023-04-09 15:36:28.900: Simlock: Unlocked
2023-04-09 15:36:29.159: Boot policy: Unsecure
2023-04-09 15:36:29.159: DB: SecureProduction
2023-04-09 15:36:29.160: DBX: SecureProduction
2023-04-09 15:36:29.160: KEK: SecureProduction
2023-04-09 15:36:29.160: PK: SecureProduction
2023-04-09 15:36:36.072: Rebooting phone to Flash mode
2023-04-09 15:36:36.075: Rebooting phone to Flash mode...
2023-04-09 15:36:39.468: Start unlock. Phone needs to switch to Flash-mode
2023-04-09 15:36:39.468: In order to start unlocking the bootloader, the phone needs to be switched to Flash-mode.
2023-04-09 15:36:41.882: Switching to Flash-mode
2023-04-09 15:36:41.883: Rebooting phone to Flash mode
2023-04-09 15:36:41.884: Rebooting phone to Flash mode...
2023-04-09 15:36:50.042: Lumia disconnected
2023-04-09 15:36:56.518: Flash App Type: FlashApp
2023-04-09 15:36:56.522: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-04-09 15:36:56.522: Device path: \\?\USB#VID_0421&PID_0714#5&3b099d30&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-04-09 15:36:56.522: Connected device: Lumia
2023-04-09 15:36:56.522: Mode: Flash
2023-04-09 15:36:56.766: Phone type: RM-1038
2023-04-09 15:36:56.766: Product code: 059W558
2023-04-09 15:36:56.766: Root key hash: B68498287D74BB4247C4F8D0C3B19C1FCBCE9AB4D770F84E795B53C594F4627C
2023-04-09 15:36:56.766: Firmware version: 02177.00000.15184.36000
2023-04-09 15:36:56.766: IMEI: 354265063491840
2023-04-09 15:36:56.766: Flash app: 2.60
2023-04-09 15:36:56.766: Flash protocol: 2.37
2023-04-09 15:36:56.766: SecureBoot: Enabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
2023-04-09 15:36:56.766: Flash app security: Enabled (FFU security: Enabled, RDC: Not found, Authenticated: False)
2023-04-09 15:36:56.766: JTAG: Disabled
2023-04-09 15:36:56.851: Security flags: 0x00007BFF
2023-04-09 15:36:57.159: Platform Name: Nokia.MSM8926.P6164.1.1
2023-04-09 15:36:57.178: Public ID: A1 FA 2A 0E 93 D8 84 83 A6 DD D9 52 19 D1 2A A5 AC A7 55 D3
2023-04-09 15:36:57.203: Root Key Hash: B6 84 98 28 7D 74 BB 42 47 C4 F8 D0 C3 B1 9C 1F CB CE 9A B4 D7 70 F8 4E 79 5B 53 C5 94 F4 62 7C
2023-04-09 15:36:57.203: Platform Secure Boot Status: True
2023-04-09 15:36:57.203: Uefi Secure Boot Status: True
2023-04-09 15:36:57.203: Effective Secure Boot Status: True
2023-04-09 15:36:57.204: Bootloader Security Qfuse Status: True
2023-04-09 15:36:57.204: Bootloader Security Authentication Status: False
2023-04-09 15:36:57.204: Bootloader Security Rdc Status: False
2023-04-09 15:36:57.204: Effective Bootloader Security Status: True
2023-04-09 15:36:57.204: Native Debug Status: False
2023-04-09 15:36:58.406: Charging status: 34% - 253 mA (charging)
2023-04-09 15:36:58.407: Bootloader: Lumia Bootloader Spec B
2023-04-09 15:36:58.407: ProductCode: 059W558
2023-04-09 15:36:58.408: ProductType: RM-1038
2023-04-09 15:37:25.928: Getting Emergency files for: RM-1038
2023-04-09 15:37:26.404: Firehose-programmer-file: https://repairavoidance.blob.core.windows.net/packages/EmergencyFlash/RM-1038/MPRG8x26_fh.ede
2023-04-09 15:37:26.405: Firehose-payload-file: https://repairavoidance.blob.core.windows.net/packages/EmergencyFlash/RM-1038/RM1038_fh.edp
2023-04-09 15:38:23.604: Getting Emergency files for: RM-1038
2023-04-09 15:38:23.724: Firehose-programmer-file: https://repairavoidance.blob.core.windows.net/packages/EmergencyFlash/RM-1038/MPRG8x26_fh.ede
2023-04-09 15:38:23.724: Firehose-payload-file: https://repairavoidance.blob.core.windows.net/packages/EmergencyFlash/RM-1038/RM1038_fh.edp
2023-04-09 15:41:10.771: Getting Emergency files for: RM-1041
2023-04-09 15:41:11.279: Firehose-programmer-file: https://repairavoidance.blob.core.windows.net/packages/EmergencyFlash/RM-1041/MPRG8x26_fh.ede
2023-04-09 15:41:11.279: Firehose-payload-file: https://repairavoidance.blob.core.windows.net/packages/EmergencyFlash/RM-1041/RM1041_fh.edp
2023-04-09 15:41:59.033: Windows Phone Internals version 2.9.7894.11970
2023-04-09 15:41:59.046: Copyright Heathcliff74 / wpinternals.net
2023-04-09 15:41:59.284: Flash App Type: FlashApp
2023-04-09 15:41:59.289: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-04-09 15:41:59.289: Device path: \\?\usb#vid_0421&pid_0714#5&3b099d30&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-04-09 15:41:59.289: Connected device: Lumia
2023-04-09 15:41:59.289: Mode: Flash
2023-04-09 15:41:59.377: Security flags: 0x00007BFF
2023-04-09 15:41:59.712: Platform Name: Nokia.MSM8926.P6164.1.1
2023-04-09 15:41:59.743: Public ID: A1 FA 2A 0E 93 D8 84 83 A6 DD D9 52 19 D1 2A A5 AC A7 55 D3
2023-04-09 15:41:59.881: Root Key Hash: B6 84 98 28 7D 74 BB 42 47 C4 F8 D0 C3 B1 9C 1F CB CE 9A B4 D7 70 F8 4E 79 5B 53 C5 94 F4 62 7C
2023-04-09 15:41:59.882: Platform Secure Boot Status: True
2023-04-09 15:41:59.882: Uefi Secure Boot Status: True
2023-04-09 15:41:59.882: Effective Secure Boot Status: True
2023-04-09 15:41:59.882: Bootloader Security Qfuse Status: True
2023-04-09 15:41:59.883: Bootloader Security Authentication Status: False
2023-04-09 15:41:59.883: Bootloader Security Rdc Status: False
2023-04-09 15:41:59.883: Effective Bootloader Security Status: True
2023-04-09 15:41:59.883: Native Debug Status: False
2023-04-09 15:42:00.346: Charging status: 29% - 39 mA (charging)
2023-04-09 15:42:00.536: Phone type: RM-1038
2023-04-09 15:42:00.536: Product code: 059W558
2023-04-09 15:42:00.536: Root key hash: B68498287D74BB4247C4F8D0C3B19C1FCBCE9AB4D770F84E795B53C594F4627C
2023-04-09 15:42:00.536: Firmware version: 02177.00000.15184.36000
2023-04-09 15:42:00.536: IMEI: 354265063491840
2023-04-09 15:42:00.536: Flash app: 2.60
2023-04-09 15:42:00.536: Flash protocol: 2.37
2023-04-09 15:42:00.536: SecureBoot: Enabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
2023-04-09 15:42:00.536: Flash app security: Enabled (FFU security: Enabled, RDC: Not found, Authenticated: False)
2023-04-09 15:42:00.536: JTAG: Disabled
2023-04-09 15:42:00.537: Bootloader: Lumia Bootloader Spec B
2023-04-09 15:42:00.537: ProductCode: 059W558
2023-04-09 15:42:00.537: ProductType: RM-1038
2023-04-09 15:44:48.355: Effective Bootloader Security Status: True
2023-04-09 15:45:22.754: Effective Bootloader Security Status: True
2023-04-09 15:46:22.351: Bootloader was not unlocked. First unlock bootloader before you try to switch to Mass Storage Mode.
2023-04-09 16:21:28.527: Aborting.
2023-04-09 16:22:19.123: Getting Emergency files for: RM-1041
2023-04-09 16:22:19.592: Firehose-programmer-file: https://repairavoidance.blob.core.windows.net/packages/EmergencyFlash/RM-1041/MPRG8x26_fh.ede
2023-04-09 16:22:19.592: Firehose-payload-file: https://repairavoidance.blob.core.windows.net/packages/EmergencyFlash/RM-1041/RM1041_fh.edp
2023-04-09 17:07:02.618: Effective Bootloader Security Status: True
2023-04-09 17:07:13.182: Rebooting phone to Normal mode
2023-04-09 17:07:13.186: Rebooting phone to Normal mode...
2023-04-09 17:07:13.406: Lumia disconnected
2023-04-09 17:07:17.280: Flash App Type: BootManager
2023-04-09 17:07:17.281: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-04-09 17:07:17.281: Device path: \\?\USB#VID_0421&PID_0714#5&3b099d30&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-04-09 17:07:17.281: Connected device: Lumia
2023-04-09 17:07:17.281: Mode: Bootloader
2023-04-09 17:07:29.039: Lumia disconnected
2023-04-09 17:07:51.249: Found device on interface: 08324f9c-b621-435c-859b-ae4652481b7c
2023-04-09 17:07:51.249: Device path: \\?\USB#VID_0421&PID_06FC&MI_03#6&1b948965&0&0003#{08324f9c-b621-435c-859b-ae4652481b7c}
2023-04-09 17:07:51.249: Connected device: Lumia
2023-04-09 17:07:51.249: Mode: Normal
2023-04-09 17:07:51.779: Operator: 000-IT
2023-04-09 17:07:51.785: Manufacturer Model Name: RM-1038_1012
2023-04-09 17:07:54.807: Product Code: 059W558
2023-04-09 17:07:54.818: Firmware: 02177.00000.15184.36004
2023-04-09 17:07:54.831: HWID: 1000
2023-04-09 17:07:54.954: IMEI: 354265063491840
2023-04-09 17:07:55.164: Public ID: A1 FA 2A 0E 93 D8 84 83 A6 DD D9 52 19 D1 2A A5 AC A7 55 D3
2023-04-09 17:07:55.173: Bluetooth MAC: D0 92 9E 7E 7C 93
2023-04-09 17:07:55.243: WLAN MAC 1: D0 92 9E 80 CC 9C
2023-04-09 17:07:55.302: WLAN MAC 2: D0 92 9E 80 CC 9D
2023-04-09 17:07:55.335: WLAN MAC 3: D0 92 9E 80 CC 9E
2023-04-09 17:07:55.384: WLAN MAC 4: D0 92 9E 80 CC 9F
2023-04-09 17:07:55.405: Bootloader Security: Enabled
2023-04-09 17:07:55.414: Simlock: Unlocked
2023-04-09 17:07:55.785: Boot policy: Unsecure
2023-04-09 17:07:55.786: DB: SecureProduction
2023-04-09 17:07:55.786: DBX: SecureProduction
2023-04-09 17:07:55.786: KEK: SecureProduction
2023-04-09 17:07:55.786: PK: SecureProduction
2023-04-09 17:13:27.628: Lumia disconnected
2023-04-09 17:13:32.056: Mass storage arrived: \\.\E:
2023-04-09 17:13:32.056: Start new thread for getting metadata.
2023-04-09 17:13:32.056: Mass storage arrived: \\.\E:
2023-04-09 17:13:32.056: Start new thread for getting metadata.
2023-04-09 17:13:32.056: Mass storage arrived: \\.\E:
2023-04-09 17:13:32.056: Start new thread for getting metadata.
2023-04-09 17:13:32.056: Mass storage arrived: \\.\E:
2023-04-09 17:13:32.056: Start new thread for getting metadata.
2023-04-09 17:13:32.057: Mass storage arrived: \\.\E:
2023-04-09 17:13:32.057: Start new thread for getting metadata.
2023-04-09 17:13:32.057: Mass storage arrived: \\.\E:
2023-04-09 17:13:32.057: Start new thread for getting metadata.
2023-04-09 17:13:32.057: Mass storage arrived: \\.\E:
2023-04-09 17:13:32.057: Start new thread for getting metadata.
2023-04-09 17:13:32.057: Mass storage arrived: \\.\E:
2023-04-09 17:13:32.057: Start new thread for getting metadata.
2023-04-09 17:13:32.057: Mass storage arrived: \\.\E:
2023-04-09 17:13:32.057: Start new thread for getting metadata.
2023-04-09 17:13:48.736: Found device on interface: 08324f9c-b621-435c-859b-ae4652481b7c
2023-04-09 17:13:48.737: Device path: \\?\USB#VID_0421&PID_06FC&MI_03#6&1b948965&0&0003#{08324f9c-b621-435c-859b-ae4652481b7c}
2023-04-09 17:13:48.737: Connected device: Lumia
2023-04-09 17:13:48.737: Mode: Normal
2023-04-09 17:13:48.755: Operator: 000-IT
2023-04-09 17:13:48.760: Manufacturer Model Name: RM-1038_1012
2023-04-09 17:13:48.857: Product Code: 059W558
2023-04-09 17:13:48.859: Firmware: 02177.00000.15184.36004
2023-04-09 17:13:48.870: HWID: 1000
2023-04-09 17:13:48.886: IMEI: 354265063491840
2023-04-09 17:13:48.890: Public ID: A1 FA 2A 0E 93 D8 84 83 A6 DD D9 52 19 D1 2A A5 AC A7 55 D3
2023-04-09 17:13:48.895: Bluetooth MAC: D0 92 9E 7E 7C 93
2023-04-09 17:13:48.908: WLAN MAC 1: D0 92 9E 80 CC 9C
2023-04-09 17:13:48.921: WLAN MAC 2: D0 92 9E 80 CC 9D
2023-04-09 17:13:48.939: WLAN MAC 3: D0 92 9E 80 CC 9E
2023-04-09 17:13:48.952: WLAN MAC 4: D0 92 9E 80 CC 9F
2023-04-09 17:13:48.964: Bootloader Security: Enabled
2023-04-09 17:13:48.969: Simlock: Unlocked
2023-04-09 17:13:49.158: Boot policy: Unsecure
2023-04-09 17:13:49.158: DB: SecureProduction
2023-04-09 17:13:49.158: DBX: SecureProduction
2023-04-09 17:13:49.159: KEK: SecureProduction
2023-04-09 17:13:49.159: PK: SecureProduction
2023-04-09 17:14:51.221: Rebooting phone to Flash mode
2023-04-09 17:14:51.228: Rebooting phone to Flash mode...
2023-04-09 17:14:55.830: Lumia disconnected
2023-04-09 17:15:02.302: Flash App Type: FlashApp
2023-04-09 17:15:02.306: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-04-09 17:15:02.306: Device path: \\?\USB#VID_0421&PID_0714#5&3b099d30&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-04-09 17:15:02.306: Connected device: Lumia
2023-04-09 17:15:02.306: Mode: Flash
2023-04-09 17:15:02.386: Security flags: 0x00007BFF
2023-04-09 17:15:02.704: Platform Name: Nokia.MSM8926.P6164.1.1
2023-04-09 17:15:02.722: Public ID: A1 FA 2A 0E 93 D8 84 83 A6 DD D9 52 19 D1 2A A5 AC A7 55 D3
2023-04-09 17:15:02.740: Root Key Hash: B6 84 98 28 7D 74 BB 42 47 C4 F8 D0 C3 B1 9C 1F CB CE 9A B4 D7 70 F8 4E 79 5B 53 C5 94 F4 62 7C
2023-04-09 17:15:02.740: Platform Secure Boot Status: True
2023-04-09 17:15:02.740: Uefi Secure Boot Status: True
2023-04-09 17:15:02.740: Effective Secure Boot Status: True
2023-04-09 17:15:02.740: Bootloader Security Qfuse Status: True
2023-04-09 17:15:02.740: Bootloader Security Authentication Status: False
2023-04-09 17:15:02.740: Bootloader Security Rdc Status: False
2023-04-09 17:15:02.740: Effective Bootloader Security Status: True
2023-04-09 17:15:02.740: Native Debug Status: False
2023-04-09 17:15:03.927: Charging status: 17% - 253 mA (charging)
2023-04-09 17:15:04.117: Phone type: RM-1038
2023-04-09 17:15:04.118: Product code: 059W558
2023-04-09 17:15:04.118: Root key hash: B68498287D74BB4247C4F8D0C3B19C1FCBCE9AB4D770F84E795B53C594F4627C
2023-04-09 17:15:04.118: Firmware version: 02177.00000.15184.36000
2023-04-09 17:15:04.118: IMEI: 354265063491840
2023-04-09 17:15:04.118: Flash app: 2.60
2023-04-09 17:15:04.118: Flash protocol: 2.37
2023-04-09 17:15:04.118: SecureBoot: Enabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
2023-04-09 17:15:04.118: Flash app security: Enabled (FFU security: Enabled, RDC: Not found, Authenticated: False)
2023-04-09 17:15:04.118: JTAG: Disabled
2023-04-09 17:15:04.118: Bootloader: Lumia Bootloader Spec B
2023-04-09 17:15:04.118: ProductCode: 059W558
2023-04-09 17:15:04.118: ProductType: RM-1038
2023-04-09 17:15:30.605: Effective Bootloader Security Status: True
2023-04-09 17:15:34.468: Bootloader was not unlocked. First unlock bootloader before you try to switch to Mass Storage Mode.
2023-04-09 17:16:05.951: Error: Bad FFU file
2023-04-09 17:16:05.951: Bad FFU file: C:\ProgramData\WPInternals\Repository\RM-1041\RM1041_fh.edp.
Format of the executable (.exe) or library (.dll) is invalid.
2023-04-09 17:16:05.979:    at WPinternals.FFU..ctor(String Path)
   at WPinternals.WPinternalsConfig.AddFfuToRepository(String FFUPath)
2023-04-09 17:16:05.979:     Error: Format of the executable (.exe) or library (.dll) is invalid.
2023-04-09 17:16:05.979:        at WPinternals.FFU..ctor(String Path)
2023-04-09 17:16:05.980: Adding emergency files to repository: C:\ProgramData\WPInternals\Repository\RM-1041\MPRG8x26_fh.ede
2023-04-09 17:16:05.980: Type: RM-1038
2023-04-09 17:16:06.089: Unlock Bootloader
2023-04-09 17:16:06.089: Processing resources:
2023-04-09 17:16:06.089: Profile FFU: C:\ProgramData\WPInternals\Repository\RM-1041\RM1041_fh.edp
2023-04-09 17:16:06.089: EDE file: C:\ProgramData\WPInternals\Repository\RM-1041\MPRG8x26_fh.ede
2023-04-09 17:16:06.115: Error: Bad FFU file
2023-04-09 17:16:06.116: Bad FFU file: C:\ProgramData\WPInternals\Repository\RM-1041\RM1041_fh.edp.
Format of the executable (.exe) or library (.dll) is invalid.
2023-04-09 17:16:06.117:    at WPinternals.FFU..ctor(String Path)
   at WPinternals.LumiaUnlockBootloaderViewModel.LumiaUnlockUEFI(PhoneNotifierViewModel Notifier, String ProfileFFUPath, String EDEPath, String SupportedFFUPath, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus, ExitSuccess ExitSuccess, ExitFailure ExitFailure, Boolean ExperimentalSpecBEFIESPUnlock, Boolean ExperimentalSpecAEFIESPUnlock, Boolean ReUnlockDevice)
2023-04-09 17:16:06.117:     Error: Format of the executable (.exe) or library (.dll) is invalid.
2023-04-09 17:16:06.117:        at WPinternals.FFU..ctor(String Path)
2023-04-09 17:16:06.118: Bad FFU file

**Comment by StarNumber12046** [comment]
![image](https://user-images.githubusercontent.com/64470722/230781544-abc35e94-a402-4f4e-93e1-2ff7f63ab300.png)

**Comment by gus33000** [comment]
This is working as expected. You need a donor ffu with a supported os version (does not have to be for the same device either)
