### ISSUE TITLE
failed to write to pipe 4e4f4b5846

### ISSUE THREAD

**Issue by xplanthris-zz** [ReneLergner/WPinternals#50]
### Description

The bootloader fails to unlock every time on two laptops with the same error of failed to write to pipe 4r4f4b584652004

### Steps To Reproduce

Go to unlock the bootloader
add all the required files
start
wait
get the error after it attempts to flash the unlocked bootloader (part 1)

### Expected behavior

The bootloader should be unlocked normally.

### WPinternals Version

v2.9.2

### Windows Version

Windows 11 22H2 22621.1702

### Phone model

Lumia 550 

### Relevant Assets

2023-05-27 12:16:49.215: Windows Phone Internals version 2.9.7894.11970
2023-05-27 12:16:49.219: Copyright Heathcliff74 / wpinternals.net
2023-05-27 12:16:49.381: Flash App Type: FlashApp
2023-05-27 12:16:49.388: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:16:49.388: Device path: \\?\usb#vid_045e&pid_0a02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:16:49.388: Connected device: Lumia
2023-05-27 12:16:49.388: Mode: Flash
2023-05-27 12:16:49.472: Security flags: 0x00004BFF
2023-05-27 12:16:49.788: Platform Name: Microsoft.MSM8909.P6236.2.0
2023-05-27 12:16:49.808: Public ID: F0 BF 21 02 92 C6 04 C5 7F 4D 19 56 9A 22 46 20 11 25 DD 9C
2023-05-27 12:16:49.826: Root Key Hash: 56 BD C3 74 62 26 E0 80 14 6D 4D 30 C8 C8 43 26 57 A5 28 2F 05 0B 19 94 CF E8 49 71 C5 86 FA B9
2023-05-27 12:16:49.826: Platform Secure Boot Status: True
2023-05-27 12:16:49.826: Uefi Secure Boot Status: True
2023-05-27 12:16:49.827: Effective Secure Boot Status: True
2023-05-27 12:16:49.827: Bootloader Security Qfuse Status: True
2023-05-27 12:16:49.827: Bootloader Security Authentication Status: False
2023-05-27 12:16:49.827: Bootloader Security Rdc Status: False
2023-05-27 12:16:49.827: Effective Bootloader Security Status: True
2023-05-27 12:16:49.827: Native Debug Status: False
2023-05-27 12:16:49.980: Charging status: 9% - 1867 mA (charging)
2023-05-27 12:16:50.219: Phone type: RM-1127
2023-05-27 12:16:50.219: Product code: 059X5V9
2023-05-27 12:16:50.219: Root key hash: 56BDC3746226E080146D4D30C8C8432657A5282F050B1994CFE84971C586FAB9
2023-05-27 12:16:50.219: Firmware version: 01078.00042.16352.50000
2023-05-27 12:16:50.219: IMEI: 355132070314093
2023-05-27 12:16:50.219: Flash app: 2.75
2023-05-27 12:16:50.219: Flash protocol: 2.41
2023-05-27 12:16:50.219: SecureBoot: Enabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
2023-05-27 12:16:50.219: Flash app security: Enabled (FFU security: Enabled, RDC: Not found, Authenticated: False)
2023-05-27 12:16:50.219: JTAG: Disabled
2023-05-27 12:16:50.219: Bootloader: Lumia Bootloader Spec B
2023-05-27 12:16:50.219: ProductCode: 059X5V9
2023-05-27 12:16:50.219: ProductType: RM-1127
2023-05-27 12:17:03.388: FFU not added, because it was already present in the repository.
2023-05-27 12:17:03.388: Emergency files not added, because they were already present in the repository.
2023-05-27 12:17:03.388: Unlock Bootloader
2023-05-27 12:17:03.388: Processing resources:
2023-05-27 12:17:03.388: Profile FFU: C:\ProgramData\WPInternals\Repository\RM-1127\RM1127_1078.0042.10586.13333.15316.03531B_retail_prod_signed.ffu
2023-05-27 12:17:03.388: EDE file: C:\ProgramData\WPInternals\Repository\RM-1127\MPRG8909_fh.ede
2023-05-27 12:17:03.665: Assembling data for unlock
2023-05-27 12:17:03.665: Assembling data for unlock
2023-05-27 12:17:03.685: Attempt patch: SecureBootHack-V2-EFIESP
2023-05-27 12:17:03.689: Pattern: 0, 0
2023-05-27 12:17:03.689: Pattern: 1, 0
2023-05-27 12:17:03.689: Pattern: 2, 0
2023-05-27 12:17:03.689: Pattern: 3, 0
2023-05-27 12:17:03.689: Pattern: 4, 0
2023-05-27 12:17:03.689: Pattern: 5, 0
2023-05-27 12:17:03.689: Apply: 10.0.10586.494
2023-05-27 12:17:03.695: Edit BCD
2023-05-27 12:17:03.758: Enabling Test Signing
2023-05-27 12:17:03.758: Enabling Test Signing
2023-05-27 12:17:04.066: Initializing flash...
2023-05-27 12:17:04.066: Rebooting phone
2023-05-27 12:17:04.092: Lumia disconnected
2023-05-27 12:17:08.979: Flash App Type: FlashApp
2023-05-27 12:17:08.986: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:17:08.986: Device path: \\?\USB#VID_045E&PID_0A02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:17:08.986: Connected device: Lumia
2023-05-27 12:17:08.986: Mode: Flash
2023-05-27 12:17:09.100: Flash app: 2.75
2023-05-27 12:17:09.100: Flash protocol: 2.41
2023-05-27 12:17:09.100: SecureBoot: Enabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
2023-05-27 12:17:09.100: Flash app security: Enabled (FFU security: Enabled, RDC: Not found, Authenticated: False)
2023-05-27 12:17:09.100: JTAG: Disabled
2023-05-27 12:17:09.114: Hashing resources...
2023-05-27 12:17:09.151: Flashing profile loaded
2023-05-27 12:17:09.562: Flashing in progress!
2023-05-27 12:17:09.562: 
2023-05-27 12:17:09.658: Custom flash succeeded!
2023-05-27 12:17:09.955: Rebooting phone
2023-05-27 12:17:09.955: Phone performs hard exit
2023-05-27 12:17:10.002: Lumia disconnected
2023-05-27 12:17:10.275: Found device on interface: 71de994d-8b7c-43db-a27e-2ae7cd579a0c
2023-05-27 12:17:10.275: Device path: \\?\USB#VID_05C6&PID_9008#5&310c583c&0&1#{71de994d-8b7c-43db-a27e-2ae7cd579a0c}
2023-05-27 12:17:10.275: Connected device: Lumia
2023-05-27 12:17:10.275: Mode: Qualcomm Emergency Download 9008
2023-05-27 12:17:10.277: Sending programmer: C:\ProgramData\WPInternals\Repository\RM-1127\MPRG8909_fh.ede
2023-05-27 12:17:10.278: Protocol: 0x00000002
2023-05-27 12:17:10.278: Supported: 0x00000001
2023-05-27 12:17:10.278: MaxLength: 0x00000400
2023-05-27 12:17:10.278: Mode: 0x00000000
2023-05-27 12:17:10.362: Programmer loaded into phone memory
2023-05-27 12:17:10.363: Starting programmer
2023-05-27 12:17:10.364: Programmer being launched on phone
2023-05-27 12:17:10.366: Send Hello to programmer (1)
2023-05-27 12:17:10.366: Hello packet accepted
2023-05-27 12:17:10.527: In: <?xml version="1.0" encoding="UTF-8" ?><data><log value="Chip serial num: 3058645 (0x2eabd5)" /></data>
2023-05-27 12:17:10.528: In: <?xml version="1.0" encoding="UTF-8" ?><data><log value="VIP - Validated Image Programming is enabled - Validation is enabled." /></data>
2023-05-27 12:17:10.528: Incoming Hello-packets received
2023-05-27 12:17:10.736: Error on USB port!
2023-05-27 12:17:10.737: Device: QHSUSB__BULK - Qualcomm CDMA Technologies MSM
2023-05-27 12:17:10.737: Last written: 30375057000000000000000000000000
2023-05-27 12:17:10.749: Error: Failed to read from pipe.
2023-05-27 12:17:10.749:     Error: Failed to read pipe on WinUSB device.
2023-05-27 12:17:10.754:        at MadWizard.WinUSBNet.API.WinUSBDevice.ReadPipe(Int32 ifaceIndex, Byte pipeID, Byte[] buffer, Int32 offset, Int32 bytesToRead, UInt32& bytesRead)
   at MadWizard.WinUSBNet.USBPipe.Read(Byte[] buffer, Int32 offset, Int32 length)
2023-05-27 12:17:10.755:         Error: The semaphore timeout period has expired.
2023-05-27 12:17:10.755: Send Hello to programmer (2)
2023-05-27 12:17:10.756: Hello packet accepted
2023-05-27 12:17:10.756: In: <?xml version="1.0" encoding="UTF-8" ?><data><log value="Chip serial num: 3058645 (0x2eabd5)" /></data>
2023-05-27 12:17:10.756: In: <?xml version="1.0" encoding="UTF-8" ?><data><log value="EMMC: size_in_sectors:15269888, mfr_id:17, oem_id:0, prod_rev:0, mfr_date:0/2013" /></data>
2023-05-27 12:17:10.756: Incoming Hello-packets received
2023-05-27 12:17:10.756: In: <?xml version="1.0" encoding="UTF-8" ?><data><log value="Test mode ON" /></data>
2023-05-27 12:17:10.757: In: <?xml version="1.0" encoding="UTF-8" ?><data><response value="ACK" /></data>
2023-05-27 12:17:10.757: Incoming Hello-response received
2023-05-27 12:17:10.757: Handshake completed with programmer in testmode
2023-05-27 12:17:10.757: Rebooting phone
2023-05-27 12:17:10.757: Out: <?xml version="1.0" ?><data><power value="reset"/></data>
2023-05-27 12:17:10.757: In: <?xml version="1.0" encoding="UTF-8" ?><data><response value="ACK" /></data>
2023-05-27 12:17:10.970: Lumia disconnected
2023-05-27 12:17:14.977: Flash App Type: BootManager
2023-05-27 12:17:14.977: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:17:14.977: Device path: \\?\USB#VID_045E&PID_0A02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:17:14.977: Connected device: Lumia
2023-05-27 12:17:14.977: Mode: Bootloader
2023-05-27 12:17:15.004: Bootmanager: 2.48
2023-05-27 12:17:15.004: Bootmanager protocol: 2.6
2023-05-27 12:17:15.004: Flash app: 2.75
2023-05-27 12:17:15.004: Flash protocol: 2.41
2023-05-27 12:17:15.004: SecureBoot: Disabled (Platform Secure Boot: Disabled, UEFI Secure Boot: Disabled)
2023-05-27 12:17:15.004: Flash app security: Disabled (FFU security: Disabled, RDC: Not found, Authenticated: False)
2023-05-27 12:17:15.004: JTAG: Enabled
2023-05-27 12:17:15.267: Phone type: RM-1127
2023-05-27 12:17:15.267: Product code: 059X5V9
2023-05-27 12:17:15.267: Root key hash: 56BDC3746226E080146D4D30C8C8432657A5282F050B1994CFE84971C586FAB9
2023-05-27 12:17:15.267: Firmware version: 01078.00042.16352.50000
2023-05-27 12:17:15.267: IMEI: 355132070314093
2023-05-27 12:17:15.267: Flash app: 2.75
2023-05-27 12:17:15.267: Flash protocol: 2.41
2023-05-27 12:17:15.267: SecureBoot: Disabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
2023-05-27 12:17:15.267: Flash app security: Enabled (FFU security: Enabled, RDC: Not found, Authenticated: False)
2023-05-27 12:17:15.267: JTAG: Disabled
2023-05-27 12:17:15.302: Hashing resources...
2023-05-27 12:17:15.519: Flashing...
2023-05-27 12:17:18.275: Rebooting phone
2023-05-27 12:17:18.277: Waiting for phone to disconnect...
2023-05-27 12:17:18.309: Lumia disconnected
2023-05-27 12:17:18.309: Waiting for phone to connect...
2023-05-27 12:17:23.041: Flash App Type: BootManager
2023-05-27 12:17:23.041: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:17:23.041: Device path: \\?\USB#VID_045E&PID_0A02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:17:23.041: Connected device: Lumia
2023-05-27 12:17:23.041: Mode: Bootloader
2023-05-27 12:17:23.085: Bootmanager: 2.48
2023-05-27 12:17:23.085: Bootmanager protocol: 2.6
2023-05-27 12:17:23.085: Flash app: 2.75
2023-05-27 12:17:23.085: Flash protocol: 2.41
2023-05-27 12:17:23.085: SecureBoot: Disabled (Platform Secure Boot: Disabled, UEFI Secure Boot: Disabled)
2023-05-27 12:17:23.085: Flash app security: Disabled (FFU security: Disabled, RDC: Not found, Authenticated: False)
2023-05-27 12:17:23.085: JTAG: Enabled
2023-05-27 12:20:23.111: Error on USB port!
2023-05-27 12:20:23.111: Device: Lumia BootMgr - Microsoft
2023-05-27 12:20:23.111: Last written: 4E4F4B44
2023-05-27 12:20:23.111: Error: Failed to read from pipe.
2023-05-27 12:20:23.111:     Error: Failed to read pipe on WinUSB device.
2023-05-27 12:20:23.111:        at MadWizard.WinUSBNet.API.WinUSBDevice.ReadPipe(Int32 ifaceIndex, Byte pipeID, Byte[] buffer, Int32 offset, Int32 bytesToRead, UInt32& bytesRead)
   at MadWizard.WinUSBNet.USBPipe.Read(Byte[] buffer, Int32 offset, Int32 length)
2023-05-27 12:20:23.111:         Error: A device attached to the system is not functioning.
2023-05-27 12:20:23.112: Error on USB port!
2023-05-27 12:20:23.112: Device: Lumia BootMgr - Microsoft
2023-05-27 12:20:23.112: Last written: 4E4F4B56
2023-05-27 12:20:23.112: Error: Failed to write to pipe: 4E4F4B56
2023-05-27 12:20:23.112:     Error: Failed to write pipe on WinUSB device.
2023-05-27 12:20:23.112:        at MadWizard.WinUSBNet.API.WinUSBDevice.WritePipe(Int32 ifaceIndex, Byte pipeID, Byte[] buffer, Int32 offset, Int32 length)
   at MadWizard.WinUSBNet.USBPipe.Write(Byte[] buffer, Int32 offset, Int32 length)
2023-05-27 12:20:23.112:         Error: A device which does not exist was specified.
2023-05-27 12:20:23.113: Error: Failed to write to pipe: 4E4F4B56
2023-05-27 12:20:23.116:    at MadWizard.WinUSBNet.USBPipe.LogAndThrowException(Exception Ex)
   at MadWizard.WinUSBNet.USBPipe.Write(Byte[] buffer, Int32 offset, Int32 length)
   at WPinternals.NokiaPhoneModel.ExecuteRawMethod(Byte[] RawMethod, Int32 Length)
   at WPinternals.NokiaPhoneModel.ExecuteRawMethod(Byte[] RawMethod)
   at WPinternals.NokiaFlashModel.ReadPhoneInfo(Boolean ExtendedInfo)
   at WPinternals.SwitchModeViewModel.SwitchFromFlashToMassStorageMode(Boolean Continuation)
   at WPinternals.SwitchModeViewModel.StartSwitch()
   at WPinternals.SwitchModeViewModel..ctor(PhoneNotifierViewModel PhoneNotifier, Nullable`1 TargetMode, ModeSwitchProgressHandler ModeSwitchProgress, ModeSwitchErrorHandler ModeSwitchError, ModeSwitchSuccessHandler ModeSwitchSuccess, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus)
   at WPinternals.SwitchModeViewModel.SwitchToWithStatus(PhoneNotifierViewModel Notifier, Nullable`1 TargetMode, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus, String RequestedVolumeForMassStorage)
   at WPinternals.LumiaUnlockBootloaderViewModel.LumiaUnlockUEFI(PhoneNotifierViewModel Notifier, String ProfileFFUPath, String EDEPath, String SupportedFFUPath, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus, ExitSuccess ExitSuccess, ExitFailure ExitFailure, Boolean ExperimentalSpecBEFIESPUnlock, Boolean ExperimentalSpecAEFIESPUnlock, Boolean ReUnlockDevice)
2023-05-27 12:20:23.116:     Error: Failed to write pipe on WinUSB device.
2023-05-27 12:20:23.116:        at MadWizard.WinUSBNet.API.WinUSBDevice.WritePipe(Int32 ifaceIndex, Byte pipeID, Byte[] buffer, Int32 offset, Int32 length)
   at MadWizard.WinUSBNet.USBPipe.Write(Byte[] buffer, Int32 offset, Int32 length)
2023-05-27 12:20:23.116:         Error: A device which does not exist was specified.
2023-05-27 12:20:23.116: Problem detected, rolling back...
2023-05-27 12:20:23.119: Error on USB port!
2023-05-27 12:20:23.119: Device: Lumia BootMgr - Microsoft
2023-05-27 12:20:23.119: Last written: 4E4F4B56
2023-05-27 12:20:23.119: Error: Failed to write to pipe: 4E4F4B56
2023-05-27 12:20:23.119:     Error: Failed to write pipe on WinUSB device.
2023-05-27 12:20:23.119:        at MadWizard.WinUSBNet.API.WinUSBDevice.WritePipe(Int32 ifaceIndex, Byte pipeID, Byte[] buffer, Int32 offset, Int32 length)
   at MadWizard.WinUSBNet.USBPipe.Write(Byte[] buffer, Int32 offset, Int32 length)
2023-05-27 12:20:23.119:         Error: A device which does not exist was specified.
2023-05-27 12:20:23.119: Error: Failed to write to pipe: 4E4F4B56
2023-05-27 12:20:23.120:    at MadWizard.WinUSBNet.USBPipe.LogAndThrowException(Exception Ex)
   at MadWizard.WinUSBNet.USBPipe.Write(Byte[] buffer, Int32 offset, Int32 length)
   at WPinternals.NokiaPhoneModel.ExecuteRawMethod(Byte[] RawMethod, Int32 Length)
   at WPinternals.NokiaPhoneModel.ExecuteRawMethod(Byte[] RawMethod)
   at WPinternals.NokiaFlashModel.ReadPhoneInfo(Boolean ExtendedInfo)
   at WPinternals.LumiaUnlockBootloaderViewModel.LumiaFlashParts(PhoneNotifierViewModel Notifier, String FFUPath, Boolean PerformFullFlashFirst, Boolean SkipWrite, List`1 Parts, Boolean DoResetFirst, Boolean ClearFlashingStatusAtEnd, Boolean CheckSectorAlignment, Boolean ShowProgress, Boolean Experimental, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus, ExitSuccess ExitSuccess, ExitFailure ExitFailure, String EDEPath)
   at WPinternals.LumiaUnlockBootloaderViewModel.LumiaUnlockUEFI(PhoneNotifierViewModel Notifier, String ProfileFFUPath, String EDEPath, String SupportedFFUPath, SetWorkingStatus SetWorkingStatus, UpdateWorkingStatus UpdateWorkingStatus, ExitSuccess ExitSuccess, ExitFailure ExitFailure, Boolean ExperimentalSpecBEFIESPUnlock, Boolean ExperimentalSpecAEFIESPUnlock, Boolean ReUnlockDevice)
2023-05-27 12:20:23.120:     Error: Failed to write pipe on WinUSB device.
2023-05-27 12:20:23.120:        at MadWizard.WinUSBNet.API.WinUSBDevice.WritePipe(Int32 ifaceIndex, Byte pipeID, Byte[] buffer, Int32 offset, Int32 length)
   at MadWizard.WinUSBNet.USBPipe.Write(Byte[] buffer, Int32 offset, Int32 length)
2023-05-27 12:20:23.120:         Error: A device which does not exist was specified.
2023-05-27 12:20:23.121: Failed to write to pipe: 4E4F4B56
2023-05-27 12:20:23.138: Lumia disconnected
2023-05-27 12:21:06.220: Flash App Type: BootManager
2023-05-27 12:21:06.220: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:21:06.220: Device path: \\?\USB#VID_045E&PID_0A02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:21:06.220: Connected device: Lumia
2023-05-27 12:21:06.220: Mode: Bootloader
2023-05-27 12:21:12.209: Lumia disconnected
2023-05-27 12:21:55.313: Flash App Type: BootManager
2023-05-27 12:21:55.313: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:21:55.313: Device path: \\?\USB#VID_045E&PID_0A02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:21:55.313: Connected device: Lumia
2023-05-27 12:21:55.313: Mode: Bootloader
2023-05-27 12:22:01.310: Lumia disconnected
2023-05-27 12:22:44.511: Flash App Type: BootManager
2023-05-27 12:22:44.511: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:22:44.511: Device path: \\?\USB#VID_045E&PID_0A02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:22:44.511: Connected device: Lumia
2023-05-27 12:22:44.511: Mode: Bootloader
2023-05-27 12:22:50.503: Lumia disconnected
2023-05-27 12:23:33.679: Flash App Type: BootManager
2023-05-27 12:23:33.679: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:23:33.679: Device path: \\?\USB#VID_045E&PID_0A02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:23:33.679: Connected device: Lumia
2023-05-27 12:23:33.679: Mode: Bootloader
2023-05-27 12:23:39.664: Lumia disconnected
2023-05-27 12:24:22.867: Flash App Type: BootManager
2023-05-27 12:24:22.867: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:24:22.867: Device path: \\?\USB#VID_045E&PID_0A02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:24:22.867: Connected device: Lumia
2023-05-27 12:24:22.867: Mode: Bootloader
2023-05-27 12:24:28.860: Lumia disconnected
2023-05-27 12:25:12.027: Flash App Type: BootManager
2023-05-27 12:25:12.027: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:25:12.027: Device path: \\?\USB#VID_045E&PID_0A02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:25:12.027: Connected device: Lumia
2023-05-27 12:25:12.027: Mode: Bootloader
2023-05-27 12:25:18.011: Lumia disconnected
2023-05-27 12:25:59.535: Found device on interface: 4d1e55b2-f16f-11cf-88cb-001111000030
2023-05-27 12:25:59.535: Device path: \\?\HID#VID_05C6&PID_F006#6&14976d43&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
2023-05-27 12:25:59.535: Connected device: Lumia
2023-05-27 12:25:59.535: Mode: Qualcomm Emergency Charging F006
2023-05-27 12:26:06.821: Flash App Type: BootManager
2023-05-27 12:26:06.821: Found device on interface: 9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc
2023-05-27 12:26:06.821: Device path: \\?\USB#VID_045E&PID_0A02#5&310c583c&0&1#{9e3bd5f7-9690-4fcc-8810-3e2650cd6ecc}
2023-05-27 12:26:06.821: Connected device: Lumia
2023-05-27 12:26:06.821: Mode: Bootloader
2023-05-27 12:26:12.803: Lumia disconnected

**Comment by gus33000** [comment]
What's the CPU vendor out of curiosity? AMD? Intel? What generation if possible? Trying to gather what controllers are commonly seeing this behavior, i have some ideas to tackle this as well but need to know the issue at scale

**Comment by xplanthris** [comment]
Intel

**Comment by xplanthris** [comment]
However an AMD laptop has the same problems

**Comment by gus33000** [comment]
and the generation of both?

**Comment by xplanthris** [comment]
5950X for the AMD and Core I7 10510U

**Comment by gus33000** [comment]
USB-C or USB-A controller? What's the max speed supported on both controllers?

**Comment by xplanthris** [comment]
USB-A, how do I figure out the max speed part

**Comment by gus33000** [comment]
See the answer on this page: https://superuser.com/questions/478184/verifying-usb-connection-speed-usb-3-or-usb-2

**Comment by ZecosMAX** [comment]
@gus33000 lumia 550 has a micro-usb 2.0 port shouldn't PC port even if it is USB 3.0 roll back to 2.0?

**Comment by gus33000** [comment]
> @gus33000 lumia 550 has a micro-usb 2.0 port shouldn't PC port even if it is USB 3.0 roll back to 2.0?

Yes but this isn't why I am asking above questions here. I am trying to get a repro environment going.

**Comment by xplanthris** [comment]
i couldnt get the speeds but according to one of the answers there are rates and so 
high for the intel laptop
and full for the amd

**Comment by xplanthris** [comment]
also now for other devices ive noticed that wpinternals doesnt acknoledge the device sometimes in flash mode

**Comment by immortal640** [comment]
Description
The bootloader fails to unlock every time on two laptops with the same error of failed to write to pipe 4r4f4b584652004

Steps To Reproduce
Go to unlock the bootloader
add all the required files
start
wait
get the error after it attempts to flash the unlocked bootloader (part 1)

Expected behavior
The bootloader should be unlocked normally.

WPinternals Version
v2.9.2

Windows Version
Windows 11 22H2 22621.1702

Phone model
Lumia 640XL non LTE DualSim

Relevant Assets
[WPInternals.log](https://github.com/user-attachments/files/15841919/WPInternals.log)

**Comment by gus33000** [comment]
Please try using WPinternals 3.0 preview 3, if the issue persists, please file a new issue
